stages:
  - name: build
  - name: deploy

jobs:
  include:
    - stage: build
      script: mvn clean install
    - stage: deploy
      before_script:
        - cp settings.xml $HOME/.m2/
      script:
        - mvn clean deploy;
cache:
  directories:
    - $HOME/.m2