language: java
jdk: openjdk11

install: true

stages:
  - name: test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script: mvn clean test
    - stage: deploy
      before_script:
        - cp settings.xml $HOME/.m2/
      script:
        - mvn clean deploy
cache:
  directories:
    - $HOME/.m2
