package eca.config;

/**
 * Icon type.
 *
 * @author Roman Batygin
 */
public enum IconType {

    MAIN_ICON,
    ADD_ICON,
    CLEAR_ICON,
    CONSOLE_ICON,
    COPY_ICON,
    DATA_ICON,
    DATABASE_ICON,
    DELETE_ALL_ICON,
    DELETE_ICON,
    EXIT_ICON,
    EXPERIMENT_ICON,
    FONT_ICON,
    GENERATOR_ICON,
    HISTORY_ICON,
    INFO_ICON,
    KNN_ICON,
    LOAD_ICON,
    LOGISTIC_ICON,
    MINUS_ICON,
    NET_ICON,
    NEURAL_ICON,
    OPEN_ICON,
    PLUS_ICON,
    REPLACE_ICON,
    SAVE_ICON,
    SETTINGS_ICON,
    STATISTICS_ICON,
    TREE_ICON,
    EDIT_ICON,
    COLOR_ICON,
    OPTIMAL_CLASSIFIER_ICON,
    SCATTER_ICON,
    DB_SAVE_ICON,
    ECA_SERVICE_ICON,
    ECA_SERVICE_TRACKS_ICON
}
